---

- name: install php7.4 and related packges
  apt:
    update_cache: True
    pkg:
      - git
      - apache2
      - libapache2-mod-php7.4
      - mariadb-server
      - python3-pymysql
      - php7.4
      - php7.4-cli
      - php7.4-bcmath
      - php7.4-imagick
      - php7.4-gd
      - php7.4-intl
      - php7.4-mbstring
      - php7.4-mysql
      - php7.4-xml
      - php7.4-zip
      - php7.4-dom
      - php7.4-curl
      - gettext
      - jq
    state: present
  become: True

- find:
    path: /etc/apache2/mods-enabled/
    pattern: "php*.conf"
    file_type: link
  register: _mod_php_conf_path
  tags: always

- ini_file:
    path: "/etc/php/{{ _php_version }}/apache2/php.ini"
    section: PHP
    option: "{{ item.key }}"
    value: "{{ item.value }}"
  loop: "{{ monarc_php_config | dict2items }}"
  vars:
    _php_version: "{{ _mod_php_conf_path.files[0].path | basename | splitext | first | regex_replace('^php', '') }}"
  notify: restart apache
  become: True
